version: '3.8'

services:
  web01:
    image: emmanuella00/today-i-learned-app:v1
    container_name: web01
    ports:
      - "8081:8080"
    networks:
      - app-network
    restart: unless-stopped

  web02:
    image: emmanuella00/today-i-learned-app:v1
    container_name: web02
    ports:
      - "8082:8080"
    networks:
      - app-network
    restart: unless-stopped

  lb01:
    image: haproxy:latest
    container_name: lb01
    ports:
      - "80:80"
      - "8404:8404"  # HAProxy stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - app-network
    depends_on:
      - web01
      - web02
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
